import {
	gettala,
	guessthenumber,
	meta,
	piggame,
	shopify,
	starbucks,
	tesla,
	shikshahome,
	nftlanding,
	admindashboard,
	lmsdigital,
	droit,
} from "../assets/images";
import {
	car,
	contact,
	css,
	java,
	tryidol,
	estate,
	express,
	git,
	github,
	shiksha,
	html,
	hackhazards,
	javascript,
	linkedin,
	mongodb,
	motion,
	mui,
	nextjs,
	nodejs,
	pricewise,
	react,
	redux,
	sass,
	snapgram,
	summiz,
	tailwindcss,
	threads,
	typescript,
} from "../assets/icons";

export const resumeLink = "https://drive.google.com/file/d/1g0fmuxygPC1ESO2qolMMS5UzdmUXGhPo/view?usp=sharing";

export const skills = [
	{
		imageUrl: html,
		link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
		name: "HTML",
		type: "Frontend",
	},
	{
		imageUrl: css,
		name: "CSS",
		link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
		type: "Frontend",
	},
	{
		imageUrl: sass,
		name: "Sass",
		link: "https://youtu.be/YSdo4-2cWLQ?si=29DSZ5tzpP0NEy-a",
		type: "Frontend",
	},
	{
		imageUrl: tailwindcss,
		name: "Tailwind CSS",
		link: "https://youtu.be/tS7upsfuxmo?si=S2BY34jiraFgcMJ-",
		type: "Frontend",
	},
	{
		imageUrl: mui,
		name: "Material-UI",
		link: "https://mui.com/material-ui/getting-started/usage/",
		type: "Frontend",
	},
	{
		imageUrl: javascript,
		name: "JavaScript",
		link: "https://www.youtube.com/watch?v=uGRZ2CzkFUo&list=PLwGdqUZWnOp1hqyT6h7pY0RlXIIGlE5U0",
		type: "Frontend",
	},
	{
		imageUrl: typescript,
		name: "TypeScript",
		link: "https://youtu.be/66_bET6sI20?si=Mkfx83RCy92mJ-L4",
		type: "Frontend",
	},
	{
		imageUrl: react,
		name: "React",
		link: "https://www.youtube.com/watch?v=tiLWCNFzThE&list=PLwGdqUZWnOp3aROg4wypcRhZqJG3ajZWJ",
		type: "Frontend",
	},
	{
		imageUrl: motion,
		name: "Framer Motion",
		link: "https://www.framer.com/motion/",
		type: "Animation",
	},
	{
		imageUrl: redux,
		name: "Redux",
		link: "https://www.youtube.com/watch?v=pBgQhZcQxMw",
		type: "State Management",
	},
	{
		imageUrl: nodejs,
		name: "Node.js",
		link: "https://nodejs.org/docs/latest/api/",
		type: "Backend",
	},
	{
		imageUrl: express,
		name: "Express",
		link: "https://expressjs.com/",
		type: "Backend",
	},
	{
		imageUrl: mongodb,
		name: "MongoDB",
		link: "https://www.mongodb.com/docs/",
		type: "Database",
	},
	{
		imageUrl: nextjs,
		name: "Next.js",
		link: "https://nextjs.org/docs",
		type: "Frontend",
	},
	{
		imageUrl: git,
		name: "Git",
		link: "https://www.youtube.com/watch?v=r8QQOAicu8Y",
		type: "Version Control",
	},
	{
		imageUrl: java,
		name: "Java",
		link: "https://www.javatpoint.com/java-tutorial",
		type: "Languages",
	},
	{
		imageUrl: github,
		name: "GitHub",
		link: "https://www.youtube.com/watch?v=r8QQOAicu8Y",
		type: "Version Control",
	},
];

export const experiences = [
	{
		title: "Full Stack Developer Intern",
		company_name: "Droit.Care",
		location: "remote",
		icon: droit,
		iconBg: "#E4EBF2",
		date: "July 2024 - present",
		points: [
			"Directed the development and launch of droit.care website, integrating a robust platform for product promotion, resulting in a 40% increase in online engagement and a 25% boost in sales.",
			"Engineered consultancy software using Curable to optimize online consultations and enhance digital healthcare services.",
		],
		link: "https://droit.care/",
	},
	{
		title: "Full Stack Developer Intern",
		location: "onsite",
		company_name: "Tryidol Technologies",
		icon: tryidol,
		iconBg: "#accbe1",
		date: "February 2024 - July 2024",
		points: [
			"Responsible for designing and developing the company website from scratch.",
			"Engineered responsive web pages using React.js, ensuring an enhanced user experience across multiple devices.",
			"Build a CRM Application for vehicle rental services, streamlining processes for efficient bill generation and client management.",
			"I seamlessly integrated functionalities for data retrieval from both Excel and CSV files, enhancing the application&apos;s versatility and utility.",
		],
		link: "https://www.linkedin.com/company/tryidoltech/posts/?feedView=all",
	},
	{
		title: "Hackhazards Winner",
		company_name: "BPIT, Delhi",
		icon: hackhazards,
		iconBg: "#fbc3bc",
		date: "16 March 2024 - 17 March 2024",
		points: [
			"Developed 'My Air Visual', a web application aggregating air quality data from diverse sources to facilitate user understanding of air quality levels in various cities.",
			"Secured 1st place out of 150 participants in a hackathon by employing a combination of hardware and software solutions.",
			"Designed and implemented a Discord clone as part of the hackathon project.",
			"Successfully addressed a significant business problem related to pollution in Delhi, demonstrating problem-solving skills and practical application of technology for social and environmental impact.",
		],
		link: "https://drive.google.com/file/d/1mmkxNmxBhfEvLzVgRgW5RTPZojoJN1Z9/view",
	},
	{
		title: "Shiksha Arpan Web Developent Challenge",
		company_name: "BlackR Enterprises & Fixpoint Pvt Ltd.",
		icon: shiksha,
		iconBg: "#b7e4c7",
		date: "18 July 2023 - 06 August 2023",
		points: [
			"Led the design and development of the User Interface (UI) for two critical features of the Shiksha Arpan Platform, emphasizing visual appeal and user-friendliness.",
			"Crafted the UI for the Community Discussion Forum feature, fostering engagement and interaction among platform users through intuitive design and seamless navigation.",
			"Designed the UI for the Enhanced Tutor Matching Algorithm feature, ensuring ease of use and clarity in presenting tutor recommendations to users.",
		],
		link: "https://drive.google.com/file/d/1VgE8j2BNz622wQxGPTMjSfMK_4xd3mau/view",
	},
];

export const socialLinks = [
	{
		name: "Contact",
		iconUrl: contact,
		link: "/contact",
	},
	{
		name: "GitHub",
		iconUrl: github,
		link: "https://github.com/Aryan9901",
	},
	{
		name: "LinkedIn",
		iconUrl: linkedin,
		link: "https://www.linkedin.com/in/agaryan",
	},
];

export const projects = [
	{
		iconUrl: pricewise,
		imgUrl: lmsdigital,
		theme: "btn-back-red",
		name: "DIGITAL PORTFOLIO",
		description:
			"LMS Digital revolutionizes online education with its modern Learning Management System. Powered by React.js, Node.js, Express.js, and MongoDB, it offers robust course management and effective communication tools for educators and learners",
		link: "https://digital-portfolio-aqea.onrender.com/",
		github: "https://github.com/Aryan9901/lmsdigital",
		tags: ["MERN"],
		tech: ["REACT", "NODEJS", "EXPRESSJS", "MONGODB"],
	},
	{
		iconUrl: pricewise,
		imgUrl: admindashboard,
		theme: "btn-back-red",
		name: "ECOMMERCE DASHBOARD",
		description:
			"Introducing our eCommerce Dashboard: React, TypeScript, and SASS-powered. Features interactive data tables, dynamic charts, and a fun guessing game with instant feedback.",
		link: "https://react-admin-dashboard-ts-p3an.vercel.app/admin/dashboard",
		github: "https://github.com/Aryan9901/react_admin_dashboard_ts",
		tags: ["JAVASCRIPT"],
		tech: ["REACT", "TYPESCRIPT", "SASS", "REACT-TABLE", "CHART-JS-2"],
	},
	{
		iconUrl: snapgram,
		theme: "btn-back-pink",
		imgUrl: shikshahome,
		name: "SHIKSHA ARPAN",
		description:
			"The Shiksha Arpan Platform offers an intuitive, user-friendly interface featuring a Community Discussion Forum and an Enhanced Tutor Matching Algorithm for seamless academic assistance and knowledge sharing.",
		link: "https://aryan9901.github.io/Shiksha-Arpan-Web-Development-Challenge-/",
		github: "https://github.com/Aryan9901/Shiksha-Arpan-Web-Development-Challenge-",
		tags: ["UI / UX"],
		tech: ["HTML", "CSS", "JAVASCRIPT", "GSAP"],
	},
	{
		iconUrl: car,
		theme: "btn-back-blue",
		imgUrl: gettala,
		name: "GET TALA WEBSITE",
		description:
			"'Gettala' is a stylish website showcasing fruit-based snacks with GSAP animations, echoing taglines such as 'Bringing fruit snacks back to their roots,' emphasizing natural flavors and quality ingredients.",
		link: "https://aryan9901.github.io/gettala-website/",
		github: "https://github.com/Aryan9901/gettala-website",
		tags: ["UI / UX", "GSAP"],
		tech: ["HTML", "CSS", "JAVASCRIPT", "GSAP"],
	},
	{
		iconUrl: pricewise,
		imgUrl: guessthenumber,
		theme: "btn-back-red",
		name: "Guess The Number",
		description:
			"Designed a responsive guessing game using vanilla JavaScript. Users guess 1-20, receive instant feedback, track attempts, and celebrate correct guesses. Built with HTML, CSS, and JavaScript for seamless gameplay.",
		link: "https://aryan9901.github.io/guess-the-number/",
		github: "https://github.com/Aryan9901/guess-the-number",
		tags: ["JAVASCRIPT"],
		tech: ["HTML", "CSS", "JAVASCRIPT"],
	},
	{
		iconUrl: threads,
		theme: "btn-back-green",
		imgUrl: piggame,
		name: "PIG GAME",
		description:
			"Roll the dice, rack up points, but beware the dreaded 1! Strategize to be the first to reach 100 points and claim Pig Dice victory! Let the game of skill and luck begin!",
		link: "https://aryan9901.github.io/pig-game/",
		github: "https://github.com/Aryan9901/pig-game",
		tags: ["JAVASCRIPT"],
		tech: ["HTML", "CSS", "JAVASCRIPT"],
	},
	{
		iconUrl: estate,
		theme: "btn-back-black",
		name: "NFT Marketplace Landing page",
		imgUrl: nftlanding,
		description:
			"The NFT Marketplace Landing Page is a UI/UX website highlighting a fictional NFT marketplace. NFTs, unique digital assets like artwork and collectibles, are showcased, reflecting their growing significance across industries.",
		link: "https://github.com/Aryan9901/NFT-MARKETPLACE",
		github: "https://github.com/adrianhajdin/pricewise",
		tags: ["UI / UX"],
		tech: ["HTML", "CSS"],
	},
	{
		iconUrl: summiz,
		theme: "btn-back-yellow",
		imgUrl: shikshahome,
		name: "AI Summarizer Application",
		description: "App that leverages AI to automatically generate concise & informative summaries from lengthy text content, or blogs.",
		link: "https://github.com/adrianhajdin/project_ai_summarizer",
		github: "https://github.com/adrianhajdin/pricewise",
		tags: ["React JS"],
	},
];
